export const cityCodes = Object([
    {   "label": "Cairo",   "code": "EG-01" },
    {   "label": "Alexandria",   "code": "EG-02" },
    {   "label": "Sahel",   "code": "EG-03" },
    {   "label": "Behira",   "code": "EG-04" },
    {   "label": "Dakahlia",   "code": "EG-05" },
    {   "label": "El Kalioubia",   "code": "EG-06" },
    {   "label": "Gharbia",   "code": "EG-07" },
    {   "label": "Kafr Alsheikh",   "code": "EG-08" },
    {   "label": "Monufia",   "code": "EG-09" },
    {   "label": "Sharqia",   "code": "EG-10" },
    {   "label": "Isamilia",   "code": "EG-11" },
    {   "label": "Suez",   "code": "EG-12" },
    {   "label": "Port Said",   "code": "EG-13" },
    {   "label": "Damietta",   "code": "EG-14" },
    {   "label": "Fayoum",   "code": "EG-15" },
    {   "label": "Bani Suif",   "code": "EG-16" },
    {   "label": "Assuit",   "code": "EG-17" },
    {   "label": "Sohag",   "code": "EG-18" },
    {   "label": "Menya",   "code": "EG-19" },
    {   "label": "Qena",   "code": "EG-20" },
    {   "label": "Aswan",   "code": "EG-21" },
    {   "label": "Luxor",   "code": "EG-22" },
    {   "label": "New Valley",   "code": "EG-24" },
    {   "label": "Red Sea",   "code": "EG-23" }
   ])